Fix html5lib import error
Due to property may happen to be cached html5lib are not imported and causes "Caught AttributeError while rendering: 'Html5LibParser' object has no attribute 'html5lib'"
Sorry cannot provide test for that as I don't have the environment set up and am short in time to do this.