Make `compress` command (at least) run through on 1.8
FAILED (failures=15, errors=15, skipped=1)

AssertionError: 2 != 12
OfflineGenerationError: ... key "XYZ" missing ...